# Generated by Django 3.2.12 on 2022-03-07 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('elevation', models.IntegerField()),
                ('length', models.IntegerField()),
                ('fee', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('park_code', models.CharField(max_length=4, null=True)),
                ('hours', models.CharField(max_length=255)),
                ('activities', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badges', models.TextField(blank=True)),
                ('dog_friendly', models.BooleanField(default=False)),
                ('no_pets_allowed', models.BooleanField(default=False)),
                ('muddy', models.BooleanField(default=False)),
                ('rocky', models.BooleanField(default=False)),
                ('steep', models.BooleanField(default=False)),
                ('shaded', models.BooleanField(default=False)),
                ('river_crossing', models.BooleanField(default=False)),
                ('limited_parking', models.BooleanField(default=False)),
                ('ample_parking', models.BooleanField(default=False)),
                ('clean_bathrooms', models.BooleanField(default=False)),
                ('no_bathrooms', models.BooleanField(default=False)),
                ('dirty_bathrooms', models.BooleanField(default=False)),
                ('no_cell_service', models.BooleanField(default=False)),
                ('strong_cell_signal', models.BooleanField(default=False)),
                ('weak_cell_signal', models.BooleanField(default=False)),
                ('kid_friendly', models.BooleanField(default=False)),
                ('paved', models.BooleanField(default=False)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trails.trail')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trails.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trails/')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trails.trail')),
            ],
        ),
    ]
