# Generated by Django 3.2.12 on 2022-03-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='trail_type',
            field=models.CharField(blank=True, choices=[('oab', 'oab'), ('loop', 'loop'), ('seg', 'seg')], max_length=255, null=True),
        ),
    ]
