# Generated by Django 3.2.12 on 2022-03-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_trail_trail_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=255)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('fee', models.IntegerField(null=True)),
                ('park_code', models.CharField(max_length=4, null=True)),
                ('hours', models.CharField(max_length=255)),
                ('activities', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='trail',
            old_name='elevation',
            new_name='elevation_gain',
        ),
        migrations.RenameField(
            model_name='trail',
            old_name='activities',
            new_name='trail_name',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='park_code',
        ),
        migrations.AddField(
            model_name='trail',
            name='park',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trails.park'),
        ),
    ]
