# Generated by Django 3.2.12 on 2022-03-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_park_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='fee',
        ),
    ]
