# Generated by Django 3.2.12 on 2022-03-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_remove_park_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='fee',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
