# Generated by Django 3.2.12 on 2022-03-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0006_park_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='activities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='park',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='park',
            name='park_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
