# Generated by Django 3.2.12 on 2022-03-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_auto_20220307_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
