# Generated by Django 3.2.12 on 2022-03-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0008_auto_20220307_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='park_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='trail',
            old_name='trail_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userfeedack',
            name='badges',
        ),
        migrations.AlterField(
            model_name='park',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='fee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='elevation_gain',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
