# Generated by Django 3.2.12 on 2022-03-09 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0009_auto_20220309_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='park',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trails.park'),
            preserve_default=False,
        ),
    ]
