# Generated by Django 3.2.12 on 2022-03-10 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0010_alter_trail_park'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFeedack',
            new_name='UserFeedback',
        ),
    ]
