# Generated by Django 3.2.12 on 2022-03-11 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0011_rename_userfeedack_userfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='ample_parking',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='clean_bathrooms',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='dirty_bathrooms',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='dog_friendly',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='limited_parking',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='no_bathrooms',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='no_cell_service',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='no_pets_allowed',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='strong_cell_signal',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='weak_cell_signal',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('df', 'df'), ('npa', 'npa')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='cell_strength',
            field=models.CharField(blank=True, choices=[('df', 'df'), ('npa', 'npa')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='parking',
            field=models.CharField(blank=True, choices=[('df', 'df'), ('npa', 'npa')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='pet_stance',
            field=models.CharField(blank=True, choices=[('df', 'df'), ('npa', 'npa')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='trails.park'),
        ),
    ]
