# Generated by Django 3.2.12 on 2022-03-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0012_auto_20220311_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('nbath', 'nbath'), ('cbath', 'cbath'), ('dbath', 'dbath')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='cell_strength',
            field=models.CharField(blank=True, choices=[('ncell', 'ncell'), ('wcell', 'wcell'), ('scell', 'scell')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='parking',
            field=models.CharField(blank=True, choices=[('lpark', 'lpark'), ('apark', 'apark')], max_length=255, null=True),
        ),
    ]
