# Generated by Django 3.2.12 on 2022-03-13 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0014_remove_userfeedback_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail', to='trails.trail'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='trails.trail'),
        ),
    ]
