# Generated by Django 3.2.12 on 2022-03-14 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0015_auto_20220313_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
