# Generated by Django 3.2.12 on 2022-03-15 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0017_rename_time_trip_military_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='military_time',
            new_name='time',
        ),
    ]
