# Generated by Django 3.2.12 on 2022-03-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0018_rename_military_time_trip_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
