# Generated by Django 3.2.12 on 2022-03-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0020_auto_20220318_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name='park',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
    ]
